spring:
    datasource:
        url: jdbc:postgresql://10.117.16.3:5432/makromapa-auth
        username: makromapa-pay-user
        password: mysecretpassword

    flyway:
        locations: classpath:db/migration/default,classpath:db/migration/prod

makromapa-auth:
    root:
        url: https://auth.code-house.pl