spring:
    datasource:
        url: jdbc:postgresql://10.114.224.3:5432/makromapa-pay
        username: makromapa-pay-user

    flyway:
        locations: classpath:db/migration/default,classpath:db/migration/prod

makromapa-auth:
    root:
        url: https://auth.code-house.pl